PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv S1 — star-1: single-predicate star (subjects that have a type)
SELECT ?v0 WHERE {
    ?v0 rdf:type wsdbm:City .
}
