PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv S3 — star-3: 3-predicate star on an offer
SELECT ?v0 ?v1 ?v2 WHERE {
    ?v0 rdf:type     wsdbm:Offer ;
        gr:price     ?v1 ;
        sorg:seller  ?v2 .
}
