PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

# WatDiv S7 — star-7: 7-predicate star (user + purchase relation)
SELECT ?v0 ?v1 ?v2 ?v3 ?v4 ?v5 ?v6 WHERE {
    ?v0 rdf:type          wsdbm:User ;
        foaf:givenName    ?v1 ;
        wsdbm:userId      ?v2 ;
        sorg:nationality  ?v3 ;
        wsdbm:age         ?v4 ;
        wsdbm:gender      ?v5 ;
        wsdbm:makesPurchase ?v6 .
}
