PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv B10 — complex: 4-hop chain with aggregates
SELECT ?v0 (SUM(?price) AS ?totalSpend) WHERE {
    ?v0 rdf:type              wsdbm:User ;
        wsdbm:makesPurchase   ?v1 .
    ?v1 wsdbm:purchaseFor     ?v2 .
    ?v2 gr:price              ?price .
}
GROUP BY ?v0
ORDER BY DESC(?totalSpend)
LIMIT 15
