PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv B2 — complex: chain with UNION branch
SELECT ?v0 ?v1 ?v2 WHERE {
    ?v0 rdf:type wsdbm:User .
    {
        ?v0 wsdbm:makesPurchase ?v1 .
        ?v1 wsdbm:purchaseFor   ?v2 .
    } UNION {
        ?v0 wsdbm:follows       ?v1 .
        ?v1 wsdbm:makesPurchase ?v2 .
    }
}
