PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv B8 — complex: DISTINCT + ORDER BY + LIMIT
SELECT DISTINCT ?v0 ?v1 WHERE {
    ?v0 rdf:type           wsdbm:User ;
        sorg:nationality   ?v1 .
}
ORDER BY ?v1 ?v0
LIMIT 25
