PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv L1 — long chain-1: 3-hop chain
SELECT ?v0 ?v1 ?v2 ?v3 WHERE {
    ?v0 rdf:type             wsdbm:User ;
        wsdbm:follows        ?v1 .
    ?v1 wsdbm:follows        ?v2 .
    ?v2 wsdbm:makesPurchase  ?v3 .
}
LIMIT 20
