PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv L3 — long chain-3: 5-hop chain
SELECT ?v0 ?v1 ?v2 ?v3 ?v4 ?v5 WHERE {
    ?v0 rdf:type             wsdbm:User ;
        wsdbm:follows        ?v1 .
    ?v1 wsdbm:follows        ?v2 .
    ?v2 wsdbm:follows        ?v3 .
    ?v3 wsdbm:follows        ?v4 .
    ?v4 wsdbm:makesPurchase  ?v5 .
}
LIMIT 20
