PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv L4 — long chain-4: 5-hop chain ending in product details
SELECT ?v0 ?v1 ?v2 ?v3 ?v4 ?price WHERE {
    ?v0 rdf:type              wsdbm:User ;
        wsdbm:follows         ?v1 .
    ?v1 wsdbm:follows         ?v2 .
    ?v2 wsdbm:makesPurchase   ?v3 .
    ?v3 wsdbm:purchaseFor     ?v4 .
    ?v4 gr:price              ?price .
}
LIMIT 20
