PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX sorg:  <http://schema.org/>
PREFIX gr:    <http://purl.org/goodrelations/v1#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# WatDiv C2 — chain-2: 3-hop chain (user → purchase → offer → product)
SELECT ?v0 ?v1 ?v2 ?v3 WHERE {
    ?v0 rdf:type              wsdbm:User ;
        wsdbm:makesPurchase   ?v1 .
    ?v1 wsdbm:purchaseFor     ?v2 .
    ?v2 sorg:product          ?v3 .
}
