apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-ripple.fullname" . }}-secret
  labels:
    {{- include "pg-ripple.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
