-- pg_ripple--0.1.0.sql
-- Initial schema for pg_ripple v0.1.0.
-- This file is executed by CREATE EXTENSION pg_ripple.
--
-- Objects in _pg_ripple are internal; objects in pg_ripple are user-visible.

-- Guard against double-installation.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'pg_ripple') THEN
        CREATE SCHEMA pg_ripple;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = '_pg_ripple') THEN
        CREATE SCHEMA _pg_ripple;
    END IF;
END
$$;

-- ─── Dictionary ───────────────────────────────────────────────────────────────

-- Unified term dictionary: IRIs, blank nodes, and literals share one table.
-- id   = high 64 bits of XXH3-128 hash (used as the integer key everywhere)
-- hash = low  64 bits of XXH3-128 hash (stored for collision detection)
-- kind: 0=IRI 1=blank 2=literal 3=typed-literal 4=lang-literal
CREATE TABLE _pg_ripple.dictionary (
    id       BIGINT  NOT NULL,
    hash     BIGINT  NOT NULL,
    value    TEXT    NOT NULL,
    kind     SMALLINT NOT NULL DEFAULT 0,
    datatype TEXT,           -- populated for typed literals (kind=3)
    lang     TEXT,           -- populated for language-tagged literals (kind=4)
    CONSTRAINT dictionary_pkey PRIMARY KEY (id)
);

CREATE INDEX ON _pg_ripple.dictionary (value, kind);

COMMENT ON TABLE _pg_ripple.dictionary IS
    'Term dictionary: every IRI, blank node, and literal encoded as BIGINT.';

-- ─── Statement ID sequence ───────────────────────────────────────────────────

-- Globally unique statement identifiers (SIDs).  Every VP table row gets a SID
-- via DEFAULT nextval('_pg_ripple.statement_id_seq').
CREATE SEQUENCE _pg_ripple.statement_id_seq
    START 1
    INCREMENT 1
    CACHE 64
    NO CYCLE;

-- ─── Predicate catalog ───────────────────────────────────────────────────────

-- One row per unique predicate IRI seen in the graph.
-- table_oid is NULL while the predicate lives in vp_rare.
CREATE TABLE _pg_ripple.predicates (
    id           BIGINT  NOT NULL,
    table_oid    OID,           -- OID of the dedicated vp_{id} table, or NULL
    triple_count BIGINT  NOT NULL DEFAULT 0,
    CONSTRAINT predicates_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE _pg_ripple.predicates IS
    'One row per unique predicate; tracks VP table OID and triple count.';

-- ─── Rare-predicate table ────────────────────────────────────────────────────

-- Predicates with fewer than pg_ripple.vp_promotion_threshold triples are
-- consolidated here instead of getting a dedicated VP table.
CREATE TABLE _pg_ripple.vp_rare (
    p      BIGINT   NOT NULL,
    s      BIGINT   NOT NULL,
    o      BIGINT   NOT NULL,
    g      BIGINT   NOT NULL DEFAULT 0,
    i      BIGINT   NOT NULL DEFAULT nextval('_pg_ripple.statement_id_seq'),
    source SMALLINT NOT NULL DEFAULT 0   -- 0=explicit 1=inferred
);

CREATE INDEX ON _pg_ripple.vp_rare (p, s, o);
CREATE INDEX ON _pg_ripple.vp_rare (p, o, s);

COMMENT ON TABLE _pg_ripple.vp_rare IS
    'Consolidated storage for predicates below vp_promotion_threshold.';

-- ─── User-visible schema ─────────────────────────────────────────────────────

-- The pg_ripple schema already exists (created by the control file schema= key).
-- SQL functions generated by pgrx (#[pg_extern(schema = "pg_ripple")]) land here.

-- Human-readable statistics view.
CREATE VIEW pg_ripple.predicate_stats AS
SELECT
    d.value          AS predicate_iri,
    p.id             AS predicate_id,
    p.triple_count,
    CASE WHEN p.table_oid IS NOT NULL THEN true ELSE false END AS has_vp_table
FROM _pg_ripple.predicates p
JOIN _pg_ripple.dictionary d ON d.id = p.id;

COMMENT ON VIEW pg_ripple.predicate_stats IS
    'Per-predicate triple counts and storage placement.';
